name: 'Push a file to another repository'
description: 'Used for pushing a copy of a file to another repository'
inputs:
  source_file:
    description: 'Source file from the origin directory'
    required: true
  destination_repo:
    description: 'Destination repository'
    required: true
  destination_folder:
    description: 'Directory to push the file to'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push file to, defaults to main'
    required: false
  destination_branch_create:
    description: 'Destination branch to create for this commit'
    required: false
  commit_message:
    description: 'A custom message for the commit'
    required: false
  git_server:
    description: 'Git server host, default github.com'
    required: false
    default: github.com
  retry_attempts:
    description: 'Retry attempts if pushing commit failed'
    required: false
    default: "10"  
  rsync_option:
    description: 'switches for rsync.'
    default: '-avrh'
    required: false    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-file }}
    - ${{ inputs.destination-repo }}
    - ${{ inputs.destination-folder }}
    - ${{ inputs.user-email }}
    - ${{ inputs.user-name }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.destination-branch-create }}
    - ${{ inputs.commit-message }}
    - ${{ inputs.git-server }}
    - ${{ inputs.retry-attempts }}
    - ${{ inputs.rsync-option }}
branding:
  icon: 'git-commit'
  color: 'green'
