name: Install Git LFS
on:
  workflow_dispatch:
    

jobs:
  install-git-lfs:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Checkout the repository's code

      - name: Install Git LFS
        run: sudo apt-get install -y git-lfs
